# -*- coding: utf-8 -*-
"""AgeCalculator.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BZbmP4YcbG1cgRYkzv9_ws9I7PZrS-eJ
"""



"""Age Calculator"""

from datetime import datetime

def calculate_age(birth_date):
    # Get today's date
    today = datetime.today()

    # Calculate the difference in years, months, and days
    years = today.year - birth_date.year
    months = today.month - birth_date.month
    days = today.day - birth_date.day

    # Adjust for negative values in months and days
    if days < 0:
        months -= 1
        days += (today - datetime(today.year, today.month, 1)).days

    if months < 0:
        years -= 1
        months += 12

    return years, months, days

# Input: date of birth in 'YYYY-MM-DD' format
dob_input = input("Enter your date of birth (YYYY-MM-DD): ")

# Convert the input string to a datetime object
dob = datetime.strptime(dob_input, "%Y-%m-%d")

# Call the function to calculate the age
years, months, days = calculate_age(dob)

# Output the age
print(f"Your complete age is: {years} years, {months} months, and {days} days.")

"""Deploy this code to streamlit"""

import streamlit as st
from datetime import datetime

def calculate_age(birth_date):
    today = datetime.today()
    years = today.year - birth_date.year
    months = today.month - birth_date.month
    days = today.day - birth_date.day

    if days < 0:
        months -= 1
        days += (today - datetime(today.year, today.month, 1)).days

    if months < 0:
        years -= 1
        months += 12

    return years, months, days

# Streamlit app
st.title("Age Calculator")

# User input for date of birth
dob_input = st.text_input("Enter your date of birth (YYYY-MM-DD):")

# Calculate age when input is provided
if dob_input:
    try:
        dob = datetime.strptime(dob_input, "%Y-%m-%d")
        years, months, days = calculate_age(dob)
        st.write(f"Your complete age is: {years} years, {months} months, and {days} days.")
    except ValueError:
        st.error("Invalid date format. Please enter the date in 'YYYY-MM-DD' format.")